textadventure/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('textadventure/', include('textadventure.urls')),
]

textadventure/textadventure/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
        # Default, Station mit dem Namen "start"
        path('', views.station, name="station-default"),
        path('<str:name>', views.station, name="station"),
        path("savegame/<str:station_name>", views.savegame, name="savegame"),
        path("take_item/<str:item_to_take>", views.take_item, name="take_item")
]

textadventure/textadventure/models.py
from django.db import models

# Create your models here.


class Station(models.Model):
    '''
    Eine Station im Textadventure. Der Name ist eine sprechende ID,
    muss also eindeutig (unique) sein.
    '''
    name = models.CharField(max_length=50, unique=True)
    station_probability = models.BooleanField(default=False)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.TextField(null=True, default="textadventure/256x256.png")
    music = models.TextField(null=True, default="textadventure/adventure.mp3")

    def __str__(self):
        return self.name


class Choice(models.Model):
    '''
    Eine Auswahloptin. Neben dem Text zur Beschreibung enthält Sie auch den 
    Verweis auf die nächste Station.
    '''
    station = models.ForeignKey(to=Station, on_delete=models.CASCADE, related_name="choice_set")
    text = models.CharField(max_length=200)
    next_station = models.ForeignKey(to=Station, on_delete=models.CASCADE, related_name="incoming_set")
    sound = models.TextField(null=True, default="textadventure/menu-choice.mp3")

    def __str__(self):
        return f"{self.text}: {self.next_station.name}" 


class Probability(models.Model):
    choice = models.ForeignKey(to=Choice, on_delete=models.CASCADE)
    probability = models.FloatField()
    def __str__(self):
        return f"{self.choice}: {self.probability}" 


class Savegame(models.Model):
    name = models.CharField(max_length=50)
    save_station = models.CharField(max_length=50)
    def __str__(self):
        return f"{self.name}: {self.save_station}"


class InventoryItem(models.Model):
    name = models.CharField(max_length=100)
    text = models.TextField()
    station = models.ForeignKey(to=Station, on_delete=models.CASCADE)
    taken = models.BooleanField(default=False)

textadventure/textadventure/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
import random


# Create your views here.

from . import models

print("Los geht es hier: http://localhost:8000/textadventure/start")

def station(request, name="start"):
    '''
    Hier wird die passende Station geholt und ausgegeben.
    Wird kein Name übergeben, dann wird die Station 'start' geholt.
    '''
    station = get_object_or_404(models.Station, name=name) 
    savegame = models.Savegame.objects.all()
    final_random_choice= ""
    
    # Probability-Check:
    if station.station_probability == True:
        # random_number = random.uniform(0, 1)
        choice_list = []
        probability_list = []
        for choice in station.choice_set.all():
            choice_list.append(choice.next_station.name)
            for prob in choice.probability_set.all():
                probability_list.append(prob.probability)
        final_random_choice = random.choices(choice_list, probability_list, k=1)[0]

    # Inventar
    inventory = models.InventoryItem.objects.all()

    
    context = {"station": station, "savegame": savegame, "final_random_choice": final_random_choice, "inventory": inventory}
    return render(request, "textadventure/base.html", context)




def savegame(request, station_name):
    if "save_delete" in request.POST:
        save_delete = get_object_or_404(models.Savegame, name=station_name)
        save_delete.delete()
    else:
    #     if not models.Savegame.objects.filter(name=request.POST['savegame_name']):
    #         models.Savegame.objects.create(name=request.POST["savegame_name"], save_station=station_name)
    #     else:
    #         return redirect("http://127.0.0.1:8000/textadventure/"+ station_name)
        models.Savegame.objects.create(name=request.POST["savegame_name"], save_station=station_name)
    return redirect("station-default")


def take_item(request, item_to_take):
    # Items aufnehmen
    if "take_item" in request.POST:
        take_item = get_object_or_404(models.InventoryItem, name=item_to_take)
        take_item.taken = True
        take_item.save()

    station = take_item.station.name
    
    return redirect("station", station)

textadventure/textadventure/templates/textadventure/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Textadventure</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'textadventure/station.css' %}"/>
  
</head>
<body>

{% comment %} Musik {% endcomment %}
<!--<audio autoplay loop>
  <source src="{% static station.music %}" type="audio/mp3">
Your browser does not support the audio element.
</audio>-->

<div class="container"><!--container-->

    <div class="col-left">

        <div class="image-container"><!--image-container-->
            {% comment %} Bild einfügen {% endcomment %}
            {% if station.image %}
            <img src="{% static station.image %}" alt="My image">
            {% endif %}
        </div><!--image-container-->


        <div class="text-container"><!--savegame-->
        {% if station.name != "start" %}
            {% comment %} Speichern des Savegames {% endcomment %}
            <form action="{% url 'savegame' station.name %}" method="POST" >
            {% csrf_token %}
            <div class="choice-item">
                <input type="text" name="savegame_name" id="savegame_name" required>
            </div>
            <div class="choice-item">
                <input type="submit" name="savegame" value="Spiel speichern">
            </div>
            </form>
            <a href={% url "station-default" %} class="" >
                <div class="choice-item">
                    <p>Zurück zum Anfang</p>
                </div>
            </a>
        {% endif %}

        {% if station.name == "start" %}
            {% comment %} Anzeige des Savegames {% endcomment %}
            <h2>Spielstände</h2>
            
            {% for save in savegame %}
            <h3>{{save.name}}</h3>
            <ul>
               <li>
                    <a href="{{save.save_station}}" class="">
                        <div class="choice-item">
                            <p>Laden</p>
                        </div>
                    </a>
                </li> 
                <li>
                    <form action="{% url 'savegame' save.name %}" method="POST" >
                    {% csrf_token %}
                        <div class="choice-item">
                            <input type="submit" name="save_delete" value="Löschen">
                        </div>
                    </form>
                </li>
            </ul>
            {% endfor %}
            
        {% endif %}
        </div><!--text-container-->
    </div><!--col-left-->


    <div class ="col-right">
        <div class="text-container">
            <h1 class="">{{station.title}}</h1>

            <p class="">{{station.text}}</p>
            
            {% for item in station.inventoryitem_set.all %}
            {% if item.taken == False %}
            <p>
                {{item.text}}
            </p>
            {% endif %}
            {% endfor %}

        </div><!--text-container-->

        <div class="choice-container">

            {% if station.name != "start" %}

            <!--Items aufnehmen-->
            {% for item in station.inventoryitem_set.all %}
            {% if item.taken == False %}
            <form action="{% url 'take_item' item.name %}" method="POST" >
            {% csrf_token %}
            <div class="choice-item">
                <input type="submit" name="take_item" value="{{item.name}} aufnehmen">
            </div>
            </form>
            {% endif %}
            {% endfor %}
            
            {% endif %}


            {% if station.station_probability == False %}
            {% for choice in station.choice_set.all %}
            <a href="{{choice.next_station.name}}" class="">
                <div class="choice-item">
                    <p>{{choice.text}}</p>
                </div>
                </a>
            {% endfor %}
            {% endif %}

            {% if station.station_probability == True %}
            <a href="{{final_random_choice}}" class="">
                <div class="choice-item">
                    <p>Teste dein Glück</p>
                </div>
            </a>
            {% endif %}

        </div><!--choice-container-->

        <div class="text-container">
            <h3>Inventar</h3>
            <ul> 
            {% for inventoryitem in inventory %}
            {% if inventoryitem.taken == True %}
            <li>{{inventoryitem.name}}</li>
            {% endif %}
            {% endfor %}
            
        </div><!--text-container-->
        

    </div><!--col-right-->


</div><!--container-->

</body>
</html>

textadventure/textadventure/templates/textadventure/start.html
{% block start %}

<div class="">
    <div class="">
  <div class="">
    <h5 class="">{{station.title}}</h5>
    <p class="">{{station.text}}</p>
    {% for choice in station.choice_set.all %}
      <a href="{{choice.next_station.name}}" class="">{{choice.text}}</a>
    {% endfor %}
  </div>
</div>
  </div>

{% endblock %}

textadventure/textadventure/templates/textadventure/station-probability.html
{% block station-probability %}

<h5 class="card-title">{{station.title}}</h5>
<p class="card-text">{{station.text}}</p>
<a href="{{final_random_choice}}" class="">Teste dein Glück</a>

{% endblock %}

textadventure/textadventure/templates/textadventure/station.html
{% block station %}

<h5 class="">{{station.title}}</h5>
<p class="">{{station.text}}</p>

{% for choice in station.choice_set.all %}
<a href="{{choice.next_station.name}}" class="">{{choice.text}}</a>
{% endfor %}

{% endblock %}